/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AnButton: typeof import('./src/components/AnButton.vue')['default']
    AppLoading: typeof import('./src/components/layout/appLoading.vue')['default']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    AVerificationCode: typeof import('@arco-design/web-vue')['VerificationCode']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Question: typeof import('./src/components/Question.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypeIt: typeof import('./src/components/TypeIt.vue')['default']
  }
}
